/*
 * Copyright (C) 2002-2026 DogsBay Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.dogsbay.xml.review;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * The DITAVAL that keeps struck text out of a build: everything a proposal
 * marked {@code otherprops="review-deleted"} is excluded. It goes first in
 * the filter list, since DITA-OT keeps the first rule for a key. Draft
 * comments are dropped by DITA-OT's default {@code args.draft=no}; a
 * deliverable that sets {@code args.draft=yes} publishes review comments
 * like any other draft comment. Generated into the build's working directory
 * so no project file is touched.
 */
public final class ReviewDitaval {

    public static final String FILE_NAME = "review-open.ditaval";

    public static final String CONTENT = """
        <?xml version="1.0" encoding="UTF-8"?>
        <!-- Generated by DogsBay XML: leaves out text that an open review proposal deletes. -->
        <val>
          <prop att="otherprops" val="%s" action="exclude"/>
        </val>
        """.formatted(Marks.DELETED);

    private ReviewDitaval() {
    }

    /**
     * The review filter followed by {@code ditavals}, as files, for a build.
     * When the filter cannot be written the list is returned as it was.
     */
    public static List<File> prepend(List<Path> ditavals, Path workDir) {
        List<File> out = new ArrayList<>();
        try {
            out.add(write(workDir).toFile());
        } catch (IOException e) {
            System.err.println("[review] could not write " + FILE_NAME + ": " + e.getMessage());
        }
        for (Path p : ditavals) {
            out.add(p.toFile());
        }
        return out;
    }

    /** Write the filter into {@code dir} and return it. */
    public static Path write(Path dir) throws IOException {
        Files.createDirectories(dir);
        Path f = dir.resolve(FILE_NAME);
        Files.writeString(f, CONTENT, StandardCharsets.UTF_8);
        return f;
    }
}
