/*
 * Copyright (C) 2002-2026 DogsBay Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package com.dogsbay.dogsbayaieditor.samples;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.stream.Stream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * The bundled "Audacity" DITA sample project — a small, real DITA project a new
 * user can open to learn the editor (and that showcases the agent + audits via
 * its planted issues).
 *
 * <p>Shipped as a classpath resource (a {@code git archive} snapshot of
 * {@code dogsbay/dogsbay-xml-dita-tutorial}, regenerated by the Gradle
 * {@code bundleDemo} task). The sample is <em>copied</em> into a user-chosen
 * location so the user can edit it freely — opening the copy then auto-configures
 * it (DITA type, root map, {@code DITA-OT 4.3.5}) via the project auto-setup.
 */
public final class SampleProject {

    private static final Logger LOG = LoggerFactory.getLogger(SampleProject.class);

    /** Default folder name for an installed copy. */
    public static final String NAME = "audacity-demo";

    private static final String ZIP = "/com/dogsbay/dogsbayaieditor/samples/audacity-demo.zip";
    private static final String VERSION_RES = "/com/dogsbay/dogsbayaieditor/samples/audacity-demo-version.txt";

    private SampleProject() {}

    /**
     * Distinctive maps this sample ships — used to recognize an installed copy
     * (the folder can be renamed, so we key on content, not the folder name).
     */
    private static final String[] SIGNATURE_MAPS = { "audacity-guide.ditamap", "audacity-book.ditamap" };

    /** True when the sample is bundled in this build. */
    public static boolean isAvailable() {
        return SampleProject.class.getResource(ZIP) != null;
    }

    /** True when {@code folder} looks like an installed copy of this sample. */
    public static boolean isSampleFolder(File folder) {
        if (folder == null || !folder.isDirectory()) {
            return false;
        }
        for (String map : SIGNATURE_MAPS) {
            if (!new File(folder, map).isFile()) {
                return false;
            }
        }
        return true;
    }

    /** The bundled sample's version stamp (source repo short commit), or {@code "unknown"}. */
    public static String bundledVersion() {
        try (InputStream in = SampleProject.class.getResourceAsStream(VERSION_RES)) {
            if (in == null) {
                return "unknown";
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8).trim();
        } catch (Exception e) {
            return "unknown";
        }
    }

    /** Extract the bundled sample into {@code destDir} (created if absent), additive. */
    public static File install(File destDir) throws IOException {
        return install(destDir, false);
    }

    /**
     * Extract the bundled sample into {@code destDir}.
     *
     * @param destDir the directory to populate with the sample's files
     * @param clean   when true, remove {@code destDir}'s existing contents first so
     *                the result is a pristine copy (no stale/renamed files linger) —
     *                use this for an "overwrite with a fresh copy" action
     * @return {@code destDir}
     * @throws IOException if the sample isn't bundled or extraction fails
     */
    public static File install(File destDir, boolean clean) throws IOException {
        if (!isAvailable()) {
            throw new IOException("No bundled sample project in this build");
        }
        Path root = destDir.toPath().toAbsolutePath().normalize();
        if (clean && Files.isDirectory(root)) {
            // Defensive: never wipe a filesystem root or the user's home folder, whatever
            // a caller passes — the sample belongs in a dedicated subfolder.
            Path home = Path.of(System.getProperty("user.home")).toAbsolutePath().normalize();
            if (root.getParent() == null || root.equals(home)) {
                throw new IOException("Refusing to overwrite \"" + root
                        + "\" — choose a dedicated subfolder for the sample project.");
            }
            deleteContents(root);
        }
        Files.createDirectories(root);
        try (InputStream in = SampleProject.class.getResourceAsStream(ZIP);
             ZipInputStream zip = new ZipInputStream(in)) {
            ZipEntry entry;
            while ((entry = zip.getNextEntry()) != null) {
                Path target = root.resolve(entry.getName()).normalize();
                if (!target.startsWith(root)) {
                    throw new IOException("Unsafe zip entry outside target dir: " + entry.getName());
                }
                if (entry.isDirectory()) {
                    Files.createDirectories(target);
                } else {
                    Files.createDirectories(target.getParent());
                    Files.copy(zip, target, java.nio.file.StandardCopyOption.REPLACE_EXISTING);
                }
                zip.closeEntry();
            }
        }
        // Stamp the installed version so an "update if behind" check can compare later.
        String version = bundledVersion();
        try {
            Files.writeString(root.resolve(".dogsbay-sample-version"), version);
        } catch (IOException ignore) {
            // non-fatal: the sample still works without the stamp
        }
        LOG.info("Installed sample project '{}' (version {}) to {}", NAME, version, root);
        return destDir;
    }

    /** Recursively delete everything under {@code dir} (but keep {@code dir} itself). */
    private static void deleteContents(Path dir) throws IOException {
        try (Stream<Path> walk = Files.walk(dir)) {
            walk.sorted(java.util.Comparator.reverseOrder())
                .filter(p -> !p.equals(dir))
                .forEach(p -> {
                    try {
                        Files.delete(p);
                    } catch (IOException e) {
                        throw new java.io.UncheckedIOException(e);
                    }
                });
        } catch (java.io.UncheckedIOException e) {
            throw e.getCause();
        }
    }
}
