/*
 * Copyright (C) 2002-2026 DogsBay Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.dogsbay.dogsbayaieditor.services;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;

import org.junit.jupiter.api.Test;

/**
 * The Help menu offered Contents, Index, Search and Getting Started through
 * JavaHelp, reading a help set that is not shipped, so every one of them was
 * permanently disabled and the editor logged a parse failure on each start.
 * The documentation lives on the website now.
 *
 * <p>{@code MenuBuilder} needs a full application frame, so this reads the
 * source: enough to catch the menu being wired back to a help set that does
 * not exist, or the browser link being dropped.
 */
class HelpMenuTest {

    private static String menuBuilderSource() throws Exception {
        Path file = Path.of("src/main/java/com/dogsbay/dogsbayaieditor/services/MenuBuilder.java");
        assertTrue(Files.isRegularFile(file), "cannot locate MenuBuilder at " + file);
        return Files.readString(file);
    }

    @Test
    void theHelpMenuOpensTheDocumentationSite() throws Exception {
        String source = menuBuilderSource();
        assertTrue(source.contains("DOCUMENTATION_URL"),
                "the Help menu must offer the documentation, as a single URL constant");
        assertTrue(source.contains("BrowserLauncher.openURL(DOCUMENTATION_URL)"),
                "Documentation must open in a browser");
    }

    @Test
    void noJavaHelpRemains() throws Exception {
        for (String path : new String[] {
                "src/main/java/com/dogsbay/dogsbayaieditor/services/MenuBuilder.java",
                "src/main/java/com/dogsbay/dogsbayaieditor/DogsBayAIEditor.java",
                "src/main/java/com/dogsbay/dogsbayaieditor/services/ActionRegistry.java"}) {
            String source = Files.readString(Path.of(path));
            assertFalse(source.contains("javax.help"), path + " still imports JavaHelp");
            assertFalse(source.contains("HelpSet"), path + " still refers to a JavaHelp HelpSet");
            assertFalse(source.contains("HelpBroker"), path + " still refers to a JavaHelp HelpBroker");
        }
        assertFalse(Files.exists(Path.of("lib/jh.jar")), "the JavaHelp jar is back in lib/");
        assertFalse(Files.exists(Path.of(
                "src/main/java/com/dogsbay/dogsbayaieditor/actions/HelpContentsAction.java")),
                "HelpContentsAction is back");
    }

    /**
     * loader.properties is generated by syncLib from whatever is in lib/, and is
     * not committed, so a fresh clone has neither it nor the jars it would name.
     * Check the generator, and check the file only when a build has produced it.
     */
    @Test
    void loaderPropertiesIsGeneratedNotHandMaintained() throws Exception {
        String build = Files.readString(Path.of("build.gradle.kts"));
        assertTrue(build.contains("file(\"loader.properties\").writeText("),
                "syncLib must generate loader.properties: hand-maintained, it drifted into "
                        + "naming 17 jars that no longer existed");

        Path file = Path.of("loader.properties");
        if (!Files.exists(file)) {
            return;   // a clean checkout that has not run syncLib yet
        }
        String text = Files.readString(file);
        assertTrue(text.startsWith("# Generated"),
                "loader.properties is present but was not generated by syncLib");
        long missing = text.lines()
                .filter(l -> l.startsWith("libraries="))
                .flatMap(l -> java.util.Arrays.stream(l.split(";")))
                .filter(e -> e.startsWith("lib/"))
                .filter(e -> !Files.exists(Path.of(e)))
                .count();
        assertEquals(0, missing, "loader.properties names jars that are not in lib/");
    }
}
